<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerOiJWRvE\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerOiJWRvE/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerOiJWRvE.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerOiJWRvE\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerOiJWRvE\App_KernelDevDebugContainer([
    'container.build_hash' => 'OiJWRvE',
    'container.build_id' => 'c98751c4',
    'container.build_time' => 1658702488,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerOiJWRvE');
