<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerRGfPL4l\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerRGfPL4l/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerRGfPL4l.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerRGfPL4l\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerRGfPL4l\App_KernelDevDebugContainer([
    'container.build_hash' => 'RGfPL4l',
    'container.build_id' => 'e8ecc9f3',
    'container.build_time' => 1658691882,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerRGfPL4l');
