<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    'main_page' => [[], ['_controller' => 'App\\Controller\\FrontController::index'], [], [['text', '/']], [], [], []],
    'video_list' => [[], ['_controller' => 'App\\Controller\\FrontController::videoList'], [], [['text', '/video-list']], [], [], []],
    'video_details' => [[], ['_controller' => 'App\\Controller\\FrontController::videoDetails'], [], [['text', '/video-details']], [], [], []],
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', '\\d+', 'code', true], ['text', '/_error']], [], [], []],
];
